Module1 task1
htmlacademy-vue/344547-pizza-1 pull request #1
Opened 2021-07-04 19:24 UTC by MikeIv

module1-task1 complit

2021-07-04 20:17 UTC, Djaler requested changes

2021-07-04 20:17 UTC, Djaler commented on template/build/cart.html
> +<!DOCTYPE html>
не стоит коммитить файлы template/build

2021-07-04 20:17 UTC, Djaler commented on src/frontend/package-lock.json
> +  "lockfileVersion": 2,
изменения локфайла тоже не стоит коммитить. либо можно пользоваться командой `npm ci` вместо `npm install`

2021-07-04 20:17 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                <label class="dough__input dough__input--light">
эти данные должны быть подключены из json-файла

2021-07-04 20:17 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +              <h2 class="title title--small sheet__title">Выберите размер</h2>
аналогично

2021-07-04 20:17 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                  <label class="radio ingridients__input">
аналогично

2021-07-04 20:17 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                      :key="index"
в качестве ключа стоит использовать уникальное поле объекта

2021-07-04 20:17 UTC, Djaler commented on src/frontend/src/static/filling.json
> +[
json нужно перенести из src/backend/src/factory/pizza.json

2021-07-04 20:17 UTC, Djaler commented on src/frontend/src/static/columns.json
> +[
эти данные не используются

2021-07-05 20:05 UTC, Djaler commented on template/build/cart.html
> +<!DOCTYPE html>
не исправлено

2021-07-05 20:05 UTC, Djaler commented on src/frontend/package-lock.json
> +  "lockfileVersion": 2,
не исправлено

2021-07-05 20:08 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                <label class="dough__input dough__input--light">
класс `dough__input--light` задан статически, а должен проставляться динамически на основании данных из json

2021-07-05 20:08 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                  v-for="(paste, name) in dough"
имя второй переменной здесь сильно смущает. это же индекс, почему name?

2021-07-05 20:09 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                  class="diameter__input"
тут тоже должны быть динамически проставленные классы `diameter__input--small`, `diameter__input--normal` и т.д.

2021-07-05 20:10 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                    value="small"
и это значение инпута

2021-07-05 20:12 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                  :title="paste.name"
по-моему, в шаблоне не было атрибута title у label

2021-07-05 20:14 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                    value="light"
это значение инпута должно выставляться на основании данных из json

2021-07-05 20:15 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +                    <input type="radio" name="sauce" value="tomato" checked />
это значение инпута должно выставляться на основании данных из json

2021-07-05 20:16 UTC, Djaler commented on src/frontend/src/static/filling.json
> +    "icon": "filling--mushrooms",
я очень сильно не уверен, допускается ли модификация исходных json-файлов собственными данными. Думаю, тебе стоит уточнить это у авторов

2021-07-07 06:12 UTC, MikeIv commented on src/frontend/src/static/filling.json
> +    "icon": "filling--mushrooms",
Вот что ответили в Академии. "По факту вы сделали верно, добавив классы. ..."

2021-07-07 06:39 UTC, MikeIv commented on src/frontend/package-lock.json
> +  "lockfileVersion": 2,
добавил в .gitignore

2021-07-07 06:42 UTC, MikeIv commented on template/build/cart.html
> +<!DOCTYPE html>
добавил в .gitignore

2021-07-07 06:58 UTC, MikeIv commented on src/frontend/src/views/Index.vue
> +                <label class="dough__input dough__input--light">
подключил json

2021-07-07 06:58 UTC, MikeIv commented on src/frontend/src/views/Index.vue
> +                      :key="index"
исправил

2021-07-07 06:59 UTC, MikeIv commented on src/frontend/src/static/filling.json
> +[
перенес

2021-07-07 07:00 UTC, MikeIv commented on src/frontend/src/static/columns.json
> +[
убрал, но добавил misc.json, и user.json для использования в следующих задачах

2021-07-07 07:04 UTC, MikeIv commented on src/frontend/src/views/Index.vue
> +                  v-for="(paste, name) in dough"
мы же привязываемся к уникальному ключу или чего-то не понимаю?

2021-07-07 07:12 UTC, MikeIv commented on src/frontend/src/views/Index.vue
> +                    value="small"
подключил значение из json

2021-07-07 07:14 UTC, MikeIv commented on src/frontend/src/views/Index.vue
> +                  :title="paste.name"
да, лишнее, убрал

2021-07-07 07:17 UTC, MikeIv commented on src/frontend/src/views/Index.vue
> +                    value="light"
подключил данные из json

2021-07-07 07:23 UTC, MikeIv commented on src/frontend/src/views/Index.vue
> +                    <input type="radio" name="sauce" value="tomato" checked />
подключил данные из json

2021-07-07 07:38 UTC, merged